# Generated by Django 6.0.7 on 2026-08-02 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteePanel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_ops_committee_panel',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=160, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_member_photos', to='media.mediafile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='admin_ops.committeepanel')),
            ],
            options={
                'db_table': 'admin_ops_committee_member',
            },
        ),
        migrations.AddIndex(
            model_name='committeepanel',
            index=models.Index(fields=['slug'], name='idx_committee_panel_slug'),
        ),
        migrations.AddIndex(
            model_name='committeepanel',
            index=models.Index(fields=['created_at'], name='idx_committee_panel_created_at'),
        ),
        migrations.AddIndex(
            model_name='committeepanel',
            index=models.Index(fields=['status'], name='idx_committee_panel_status'),
        ),
        migrations.AddIndex(
            model_name='committeemember',
            index=models.Index(fields=['panel'], name='idx_committee_member_panel'),
        ),
        migrations.AddIndex(
            model_name='committeemember',
            index=models.Index(fields=['email'], name='idx_committee_member_email'),
        ),
        migrations.AddIndex(
            model_name='committeemember',
            index=models.Index(fields=['phone'], name='idx_committee_member_phone'),
        ),
        migrations.AddIndex(
            model_name='committeemember',
            index=models.Index(fields=['created_at'], name='idx_committee_member_created_at'),
        ),
        migrations.AddIndex(
            model_name='committeemember',
            index=models.Index(fields=['status'], name='idx_committee_member_status'),
        ),
    ]
