# Generated by Django 5.2.16 on 2026-08-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='committeemember',
            new_name='idx_committee_member_c_at',
            old_name='idx_committee_member_created_at',
        ),
        migrations.RenameIndex(
            model_name='committeepanel',
            new_name='idx_committee_panel_c_at',
            old_name='idx_committee_panel_created_at',
        ),
    ]
