# Generated by Django 6.0.7 on 2026-08-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='achievement_gallery_images', to='media.mediafile'),
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='news_images', to='media.mediafile'),
        ),
    ]
