# Generated by Django 5.2.16 on 2026-08-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_achievement_images_news_images'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='idx_contact_msg_c_at',
            old_name='idx_contact_message_created_at',
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='idx_donation_txn_id',
            old_name='idx_donation_transaction_id',
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='idx_donation_c_at',
            old_name='idx_donation_created_at',
        ),
        migrations.RenameIndex(
            model_name='gallery',
            new_name='idx_gallery_c_at',
            old_name='idx_gallery_created_at',
        ),
    ]
