# Generated by Django 6.0.7 on 2026-08-02 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShokkhomApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('applicant_name', models.CharField(max_length=160)),
                ('father_name', models.CharField(blank=True, max_length=160, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=160, null=True)),
                ('family_information', models.TextField()),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('occupation', models.CharField(max_length=160)),
                ('reason', models.TextField()),
                ('application_status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shokkhom_application_photos', to='media.mediafile')),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='shokkhom_supporting_documents', to='media.mediafile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_shokkhom_application',
                'indexes': [models.Index(fields=['created_at'], name='idx_shokkhom_created_at'), models.Index(fields=['status'], name='idx_shokkhom_status'), models.Index(fields=['application_status'], name='idx_shokkhom_application_status')],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('full_name', models.CharField(max_length=160)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('education', models.CharField(max_length=160)),
                ('occupation', models.CharField(max_length=160)),
                ('skills', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=12, null=True)),
                ('nid_or_birth_certificate', models.CharField(blank=True, max_length=64, null=True)),
                ('emergency_contact_name', models.CharField(max_length=120)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('application_status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_application_photos', to='media.mediafile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_volunteer_application',
                'indexes': [models.Index(fields=['created_at'], name='idx_volunteer_created_at'), models.Index(fields=['status'], name='idx_volunteer_status'), models.Index(fields=['application_status'], name='idx_volunteer_application_status')],
            },
        ),
    ]
