# Generated by Django 5.2.16 on 2026-08-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shokkhomapplication',
            new_name='idx_shokkhom_app_status',
            old_name='idx_shokkhom_application_status',
        ),
        migrations.RenameIndex(
            model_name='volunteerapplication',
            new_name='idx_volunteer_app_status',
            old_name='idx_volunteer_application_status',
        ),
    ]
