# Generated by Django 6.0.7 on 2026-08-02 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('original_file_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('file_type', models.CharField(max_length=80)),
                ('size', models.BigIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_media_file',
                'indexes': [models.Index(fields=['stored_file_name'], name='idx_media_stored_file_name'), models.Index(fields=['file_type'], name='idx_media_file_type'), models.Index(fields=['upload_date'], name='idx_media_upload_date'), models.Index(fields=['created_at'], name='idx_media_created_at'), models.Index(fields=['status'], name='idx_media_status')],
            },
        ),
    ]
